backend:
  name: git-gateway
  branch: prod # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: public/uploads
public_folder: /uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/blog" # The path to the folder where the documents are stored
    extension: "mdx"
    format: "frontmatter"
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    identifier_field: slug
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "hidden", default: "slug" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          required: false,
        }
      - { label: "author", name: "author", widget: "string" }
      - {
          label: "Tags",
          name: "tag",
          widget: "select",
          multiple: true,
          options: ["via-socket"],
          required: false,
        }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
      - {
          label: "Short Description",
          name: "description",
          widget: "string",
          required: true,
        }
      - { label: "Body", name: "body", widget: "markdown" }
